# -*- coding: utf-8 -*-
"""task2.final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3xPMugpj6aJ6zsXFM5yKr1oRBp4Xr8N

#Task 2

Run the following cell to import your google drive
"""

from google.colab import drive
drive.mount("/content/gdrive")

"""Run the following cell to import the necessary libraries"""

import pandas as pd
import matplotlib.pyplot as plt

"""## Task 2.1

For aspiring data scientists and machine learning enthusiasts, it is vital that they understand the coding environment. We normally use a jupyter notebook for most of our programming. To understand its importance, lets perform a small exercise.

We are given 2 datasets, they have data of certain students from 2 different branches and their respective divisions.

Download the datasets from the links given below -

Task2p1_0 - https://drive.google.com/file/d/1sCGCErnf2iC_qKUHcGLrt2O2HwuiwZYD/view?usp=sharing

Task2p1_1 - https://drive.google.com/file/d/1Kb_TcAEfsUGi-KPZpsh8pXBaxfs4AsHh/view?usp=sharing

Create a folder named 'Task2p1' in your google drive and upload the datasets 'Task2p1_0' and 'Task2p1_1' there.

###Python Script
"""

data = pd.read_csv("/content/gdrive/MyDrive/Task2p1/Task2p1_0.csv")
data
data = pd.read_csv("/content/gdrive/MyDrive/Task2p1/Task2p1_1.csv")
data

"""###Jupyter Notebook"""

data = pd.read_csv("/content/gdrive/MyDrive/Task2p1/Task2p1_0.csv")

data

data = pd.read_csv("/content/gdrive/MyDrive/Task2p1/Task2p1_1.csv")

data

"""Note the difference between the outputs you get after using the code in cell 3 as a python script and after running it line by line in a jupyter notebook.

1. In python script we read both the files in one cell and since we did not exclusively print any of the variable in which file was read ..the last variable written was printed in the output

Although no print statement it used ,it by default prints the last variable. If we want both files to be printed we need to use 
print(data) after reading file

2. In case of jupyter notebook we are reading both the data in seperate cells ...thus after 1st data is read we print the data by calling it in the next cell
similarly 2nd data in read and called in different cells
since reading and displaying both are done in different cells all the tasks are completed sucessfully even without print statement

##Task 2.2

Download the dataset of fifty random Harry Potter spells from the link given below -

https://drive.google.com/file/d/1F2YEtVZaorL0WPGxOC5vXkMSixuYkI4v/view?usp=sharing

Create a folder named 'Task2hp' in your google drive and upload the dataset there.

Observe the dataset, it is a .csv file. Using pandas library, read the .csv file into a dataframe in the next cell. 

Tip : You can make use of the Files tab in the side bar on the left to navigate through your file structure.
"""

df=pd.read_csv('/content/gdrive/MyDrive/Task2hp/Task2hp.csv')
df1=pd.DataFrame(df)

"""Display first five rows of the dataframe."""

df1.head()

"""Remove all the rows having type as 'Hex'"""

import numpy as np
l=[]
i=df1[df1['Type']=='Hex']
print(i)
l=i.index.values
for i in l:
  df1=df1.drop (i)

df1

"""Now remove the rows from the dataframe having NaN values for column 'Light'."""

l1=[]
x=df1[df1['Light'].isnull()]
l=x.index.values
for i in l:
  df1=df1.drop(i)
print(len(df1))
print(df1)

"""Filter out the spells on the basis of their Type and make a bar graph showing your analysis of the number of spells and their distribution in the five types - Charm, Jinx, Transfiguration, Curse."""

#filter
df2=df1[df1.columns[1:3]]
print(df2)
a=df1[df1['Type']=='Charm']
b=df1[df1['Type']=='Jinx']
c=df1[df1['Type']=='Transfiguration']
d=df1[df1['Type']=='Curse']
x=[len(a),len(b),len(c),len(d),]
y=['Charm', 'Jinx', 'Transfiguration', 'Curse']
df3=pd.DataFrame(y,index=x)
print(df3)

#graph

plt.bar(y,x)
plt.title('graph')
plt.xlabel('Type')
plt.ylabel('Spell')
plt.show()

